package comp603;

import java.awt.*;
import javax.swing.*;

public class BlackjackGUI extends javax.swing.JPanel {

    public BlackjackGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new JPanel();
        BJYesButton = new JButton();
        BJNoButton = new JButton();
        BJExplainText = new JTextArea();
        BJWelcomeText = new JTextArea();

        // Set the preferred size for the panel
        jPanel1.setPreferredSize(new Dimension(1000, 500));
        jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

        BJYesButton.setText("Yes");
        BJYesButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        BJYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJYesButtonActionPerformed(evt);
            }
        });

        BJNoButton.setText("No");
        BJNoButton.setAlignmentX(Component.CENTER_ALIGNMENT);
        BJNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BJNoButtonActionPerformed(evt);
            }
        });

        BJExplainText.setEditable(false);
        BJExplainText.setColumns(20);
        BJExplainText.setRows(2);
        BJExplainText.setLineWrap(true);
        BJExplainText.setWrapStyleWord(true);
        BJExplainText.setText("Would you like an explanation of how to play the game?");
        BJExplainText.setMaximumSize(BJExplainText.getPreferredSize());

        BJWelcomeText.setEditable(false);
        BJWelcomeText.setColumns(20);
        BJWelcomeText.setFont(new Font("Segoe UI", 0, 48)); // NOI18N
        BJWelcomeText.setRows(2);
        BJWelcomeText.setLineWrap(true);
        BJWelcomeText.setWrapStyleWord(true);
        BJWelcomeText.setText("Welcome to Blackjack!");
        BJWelcomeText.setMaximumSize(BJWelcomeText.getPreferredSize());

        JPanel textPanel = new JPanel();
        textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
        textPanel.add(Box.createVerticalGlue());
        textPanel.add(BJWelcomeText);
        textPanel.add(Box.createVerticalStrut(20));
        textPanel.add(BJExplainText);
        textPanel.setAlignmentX(Component.CENTER_ALIGNMENT);

        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout());
        buttonPanel.setAlignmentX(Component.CENTER_ALIGNMENT);
        buttonPanel.add(BJYesButton);
        buttonPanel.add(Box.createHorizontalStrut(50));
        buttonPanel.add(BJNoButton);

        jPanel1.add(Box.createVerticalGlue());
        jPanel1.add(textPanel);
        jPanel1.add(Box.createVerticalStrut(20));
        jPanel1.add(buttonPanel);
        jPanel1.add(Box.createVerticalGlue());

        setLayout(new BorderLayout());
        add(jPanel1, BorderLayout.CENTER);
    }// </editor-fold>                        

    private void BJNoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void BJYesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        String explanation = "<html><body style='width: 300px; padding: 10px;'>"
                + "<h2>How to Play Blackjack</h2>"
                + "<p>The goal of blackjack is to get your count closest to 21.</p>"
                + "<p>The user and dealer both get 2 cards each.</p>"
                + "<p>The user must get a higher count than the dealer to win.</p>"
                + "<p>If the user has a smaller count value than the dealer they lose.</p>"
                + "<p>Each card is worth what the rank is (e.g., 9 is worth 9 counts).</p>"
                + "<p>Cards such as Jack, Queen or King have a count value of 10.</p>"
                + "<p>Ace cards work differently.</p>"
                + "<p>If a hand with 2 cards and one of those cards is an Ace,</p>"
                + "<p>The Ace is worth 11 counts. If a hand has more than 2 cards,</p>"
                + "<p>The Ace is worth 1 count.</p>"
                + "</body></html>";

        JOptionPane.showMessageDialog(this, explanation, "Blackjack Rules", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea BJExplainText;
    private javax.swing.JButton BJNoButton;
    private javax.swing.JTextArea BJWelcomeText;
    private javax.swing.JButton BJYesButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration                   
}
